# Example Playbook written in YAML

# YAML Playbook file starts with three dashes

---

# Example targeting host
- name: Set up App Host
  hosts: host_app

# used to define where this playbook will run

  gather_facts: yes
# gathers facts/state of machine before running playbook

  become: true
# become is used to get root permission to perform tasks that may require admin access

  vars:
    ip_db:
      DB_HOST: 123.121.121.1
  
  environment: "{{ ip_db }}"

  tasks:
  - name: Update apt-get
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Installing git
    apt:
      name: git
      state: present

  - name: Installing nginx
    apt:
      name: nginx
      state: present

  - name: Synchronise app folder
    synchronize:
      src: /home/ubuntu/app/
      dest: /home/ubuntu/app/
      recursive: yes

  - name: Synchronise nginx config folder
    synchronize:
      src: /home/ubuntu/nginx_config/
      dest: /home/ubuntu/nginx_config/
      recursive: yes

  - name: Curl nodejs source
    shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

  - name: Install nodejs
    apt:
      pkg: nodejs
      state: present

  - name: Installing pm2 with npm
    npm:
      name: pm2
      global: yes

  - name: Remove default nginx config
    file:
      path: /etc/nginx/sites-available/default
      state: absent
    
  - name: Copy new nginx config
    copy:
      src: /home/ubuntu/nginx_config/proxy_config.conf
      dest: /etc/nginx/sites-available/default

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
      enabled: yes

  - name: Export DB_HOST environment variable
    shell: export DB_HOST=192.168.10.200


  - name: npm install all packages for app
    npm:
      path: /home/ubuntu/app

  - name: start app
    shell: |
      cd /home/ubuntu/app
      pm2 kill
      pm2 start app.js
