# Example Playbook written in YAML

# YAML Playbook file starts with three dashes

---

# Example targeting host
- name: Set up App Host
  hosts: host_app2

# used to define where this playbook will run

  gather_facts: yes
# gathers facts/state of machine before running playbook

  become: true
# become is used to get root permission to perform tasks that may require admin access

  tasks:
  - name: Update apt-get
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: Installing git and nginx
    apt:
      name: ['git', 'nginx']
      state: present

  - name: Curl nodejs source
    shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

  - name: Install nodejs
    apt:
      pkg: nodejs
      state: present

  - name: Installing pm2 with npm
    npm:
      name: pm2
      global: yes

  - name: Remove default nginx config
    file:
      path: /etc/nginx/sites-available/default
      state: absent
  
  - name: Create new default file
    file:
      path: /etc/nginx/sites-available/default
      state: touch
  
  - name: Write nginx config file to listen on 80
    blockinfile:
      path: /etc/nginx/sites-available/default
      block: |
        server{
          listen: 80
          server_name development.local
          location / {
            proxy_pass http://127.0.0.1:3000;
          }

        }
    notify:
      - Restart nginx
  - name: Export DB_HOST environment variable
    shell: export DB_HOST=192.168.10.200


  - name: npm install all packages for app
    npm:
      path: /home/ubuntu/app

  - name: start app
    shell: |
      cd /home/ubuntu/app
      pm2 kill
      pm2 start app.js


  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
      enabled: yes